import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '../Navbar/Navbar';
import { ThemeProvider } from '@/components/ThemeProvider/Theme';
import { SessionProvider } from '@/components/sessionProvider';
import { getServerSession } from 'next-auth';
import { Session } from 'next-auth';

import { Provider } from 'next-auth/client';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Form App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  const session = await getServerSession();
  return (
    <html lang="en">
      <body className={inter.className}>
        <SessionProvider session={session}>
      <ThemeProvider>
        <Navbar />
       
            {children}
            </ThemeProvider>
            </SessionProvider>
      </body>
    </html>
  );
}