import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Navbar from '../Navbar/Navbar';
import { ThemeProvider } from '@/components/ThemeProvider/Theme';
// import { AuthProvider } from '@/middleware/AuthContext';
// import DashboardLayout from '../Navbar/layout';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Form App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      <body className={inter.className}>

      <ThemeProvider>
        <Navbar />
      
         
            {children}
           
            </ThemeProvider>
  
      </body>
    </html>
  );
}